# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          repository: cyx7788414/cyx7788414.github.io
          ssh-key: ${{ secrets.deploy_key }}
          submodules: recursive
#       - name: clone cyx7788414.github.io.git done
#         run: |
#           git clone git@github.com:cyx7788414/cyx7788414.github.io.git
#           echo Clone Done
#       - name: update submodule
#         run: |
#           cd cyx7788414.gthub.io/
#           echo CD Done
#           git submodule update --init --recursive
#           echo Submodule Done
      - name: push
        run: |
          cd blog/
          ls -a
          git pull
          git push git@github.com:cyx7788414/cyx7788414.github.io.git HEAD:master
          echo Push Done
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
