# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          repository: cyx7788414/cyx7788414.github.io
          ssh-key: ${{ secrets.deploy_key }}
          submodules: recursive
          path: ./cyx7788414.github.io
      - name: push
        run: |
          cd ./cyx7788414.github.io
          git config --global user.email "1986340901@qq.com"
          git config --global user.name "blog actions"
          git submodule update --recursive --remote
          echo Update Done
          git add *
          git commit -m 'auto publish'
          git push
          echo Push Done
